// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQICcy1sLDmfOHKG5InZzpeaum7-uBJPo',
    appId: '1:609672077618:web:89ade7dc6c00773686f72b',
    messagingSenderId: '609672077618',
    projectId: 'scaling-612e9',
    authDomain: 'scaling-612e9.firebaseapp.com',
    storageBucket: 'scaling-612e9.firebasestorage.app',
    measurementId: 'G-B885PY0136',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5H0hKgAdVx-pegSPrvJyfJLWna0wBfs',
    appId: '1:609672077618:android:762749dc64a6a04786f72b',
    messagingSenderId: '609672077618',
    projectId: 'scaling-612e9',
    storageBucket: 'scaling-612e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRobixtLSLYMUmmCquHz1vmRUMMNXzCo',
    appId: '1:609672077618:ios:8a45d744beef00b886f72b',
    messagingSenderId: '609672077618',
    projectId: 'scaling-612e9',
    storageBucket: 'scaling-612e9.firebasestorage.app',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRobixtLSLYMUmmCquHz1vmRUMMNXzCo',
    appId: '1:609672077618:ios:8a45d744beef00b886f72b',
    messagingSenderId: '609672077618',
    projectId: 'scaling-612e9',
    storageBucket: 'scaling-612e9.firebasestorage.app',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQICcy1sLDmfOHKG5InZzpeaum7-uBJPo',
    appId: '1:609672077618:web:506f2beface8075f86f72b',
    messagingSenderId: '609672077618',
    projectId: 'scaling-612e9',
    authDomain: 'scaling-612e9.firebaseapp.com',
    storageBucket: 'scaling-612e9.firebasestorage.app',
    measurementId: 'G-HVPT6MX7J2',
  );

}