// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDML49gRf5v98WBkpd8IGzp-NuI75fdppI',
    appId: '1:706179440619:web:61e6b6a3f89a52bfee03ae',
    messagingSenderId: '706179440619',
    projectId: 'sales-bd43c',
    authDomain: 'sales-bd43c.firebaseapp.com',
    storageBucket: 'sales-bd43c.firebasestorage.app',
    measurementId: 'G-X106N3JZLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlENdkzHiCN5mRpVKWJujVYNjD123GhFM',
    appId: '1:706179440619:android:b04561d0f79a1e18ee03ae',
    messagingSenderId: '706179440619',
    projectId: 'sales-bd43c',
    storageBucket: 'sales-bd43c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1PgDVjADUWi3MRDjbfOFefzWiodvcOYk',
    appId: '1:706179440619:ios:d70a6bf660572285ee03ae',
    messagingSenderId: '706179440619',
    projectId: 'sales-bd43c',
    storageBucket: 'sales-bd43c.firebasestorage.app',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1PgDVjADUWi3MRDjbfOFefzWiodvcOYk',
    appId: '1:706179440619:ios:d70a6bf660572285ee03ae',
    messagingSenderId: '706179440619',
    projectId: 'sales-bd43c',
    storageBucket: 'sales-bd43c.firebasestorage.app',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDML49gRf5v98WBkpd8IGzp-NuI75fdppI',
    appId: '1:706179440619:web:2f5fbdc004740d5dee03ae',
    messagingSenderId: '706179440619',
    projectId: 'sales-bd43c',
    authDomain: 'sales-bd43c.firebaseapp.com',
    storageBucket: 'sales-bd43c.firebasestorage.app',
    measurementId: 'G-RLB4PSXHC1',
  );
}
